name: Deploy Serverless

on:
  push:
    branches:
      - main

env:
  AWS_REGION: me-south-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy to AWS
        run: |
          codepipelines=$(aws codepipeline list-pipelines --region $AWS_REGION | jq -r '.pipelines[].name' | grep "main-join-ana")
          for pipeline in $codepipelines; do
            aws codepipeline start-pipeline-execution --name $pipeline
            sleep 2
          done

                  
